version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mint-transfer-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mint_transfer
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - mint-transfer-network

volumes:
  mysql_data:
    driver: local

networks:
  mint-transfer-network:
    driver: bridge
